"""initial migration

Revision ID: 670817fe9139
Revises: 
Create Date: 2024-09-11 14:55:43.856867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670817fe9139'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=80), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
